---

- name: Attach deployment event 
  dynatrace_deployment:
    tenant_url: '{{tenant_url}}'
    api_token: '{{api_token}}'
    attach_rules: '{{attach_rules}}'
    deploymentVersion: '{{deploymentVersion}}'
    deploymentName: '{{deploymentName}}'
    deploymentProject: '{{deploymentProject}}'
    customProperties: '{{customProperties}}'
